### ISSUE TITLE
Support .net maui

### ISSUE THREAD

**Issue by AdamDiament** [thisisthekap/Xamarin.ExoPlayerSlim#24]
Thanks a lot for your lib. Would you consider updating it for Maui?

**Comment by thisisthekap** [comment]
We are indeed already doing the upgrade. Will be published in the near future. Unfortunately, I am not able to provide a specific release date.

**Comment by AdamDiament** [comment]
Ok that is really good to know thanks!

**Comment by thisisthekap** [comment]
The library should be available on nuget.org once https://github.com/thisisthekap/Tonestro.Maui.ExoPlayerSlim/issues/1 is done.

**Comment by AdamDiament** [comment]
Nice thanks, this will be a massive help in upgrading my Xamarin binding of the Zoom Meeting SDK to Maui. 

https://github.com/VisualService/dotnet-zoom-meeting-SDK

**Comment by AdamDiament** [comment]
> The library should be available on nuget.org once [thisisthekap/Tonestro.Maui.ExoPlayerSlim#1](https://github.com/thisisthekap/Tonestro.Maui.ExoPlayerSlim/issues/1) is done.

Hi @thisisthekap I saw that this ticket was completed, but the nuget link on the repo goes to a 404 page (https://www.nuget.org/packages/Tonestro.Maui.ExoPlayerSlim/)

**Comment by AdamDiament** [comment]
Hi @thisisthekap - sorry to bug you. Do you have any update on the nuget package availability please?

**Comment by AdamDiament** [comment]
Any update on this? The nuget page still shows not found

**Comment by thisisthekap** [comment]
Done: https://www.nuget.org/packages/Tonestro.Maui.ExoPlayerSlim/
