### ISSUE TITLE
[Enhancement] Having a way to play a video indefinitely

### ISSUE THREAD

**Issue by AlfonChitoSalano** [thisisthekap/Xamarin.ExoPlayerSlim#5]
## Summary
Would it be good to have to play a video indefinitely?

## Intended Use Case
Right we could play the video locally and via https. However, we found out that we have no way to play the video indefinitely and it would be good to have a property to tell to replay the video once the end of the video is done.

**Comment by thisisthekap** [comment]
@AlfonChitoSalano Thank you for the suggestion, will be included in the next release.
